# l=[10,22,22,55,44,8,555,44,10]
# l .append(485)
# print(l )
# l .sort()
# print(l)
# l .reverse()
# print(l)
# l .pop(4)
# print(l )
# l .remove(10)
# print(l )
n=int(input("enter a number"))
l=list(input("enter anumber"))
l.reverse()
l.pop(6)
print(l)